security:
    encoders:
        User\TweetsBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_USER:
        ROLE_ADMIN: ROLE_USER

    providers:
        main:
            entity: { class: User\TweetsBundle\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                always_use_default_target_path: true
                default_target_path: /my
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/secure_area, roles: ROLE_USER }
        - { path: ^/my, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/logout, roles: ROLE_USER }
        

