user_new:
    pattern:  /new
    defaults: { _controller: "UserTweetsBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "UserTweetsBundle:User:create" }
    requirements: { _method: post }