<?php

namespace User\TweetsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository {

    public function getEntriesQuery($user_id = null) {
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->addOrderBy('e.created');

        if (!is_null($user_id)) {
            $qb->where('e.user_link = :user_id')->setParameter('user_id', $user_id);
        }

        return $qb->getQuery();
    }

    public function getEntries($user_id = null) {
        return $this->getEntriesQuery($user_id)->getResult();
    }

}
