User\TweetsBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: User\TweetsBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            length: 25
        salt:
            type: string
            length: 255
        firstName:
            type: string
            length: 100
        lastName:
            type: string
            length: 100
        password:
            type: string
            length: 255
        email:
            type: string
            length: 60
            unique: true
        isActive:
            type: boolean
            column: is_active
        created:
            type: datetime
        updated:
            type: datetime
            nullable: true
        
    oneToMany:
        entries:
          targetEntity: Entry
          mappedBy: user_link

    lifecycleCallbacks: 
        preUpdate: [ setUpdatedValue ]


