login:
    pattern: /login
    defaults: { _controller: UserTweetsBundle:Security:login }
    requirements: 
       _method: GET|POST

login_check:
    pattern: /login_check

logout:
    pattern: /logout

profile:
    pattern: /profile
    defaults: { _controller: UserTweetsBundle:Main:profile }

index:
    pattern: /
    defaults: { _controller: UserTweetsBundle:Main:index }

my_tweets:
    pattern: /my
    defaults: { _controller: UserTweetsBundle:Main:myTweets }

users:
    prefix: /api
    type:   rest
    resource: User\TweetsBundle\Controller\RestController

