User\TweetsBundle\Entity\User:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~            
        username:
            - NotBlank: ~
            - Unique: ~
        email:
            - Email: ~
            - Unique: ~
        password:
            - Length: 
                min: 6